const Video = require("./video.model");
const User = require("../user/user.model");
const ApiError = require("../../utils/ApiError");
const {
  uploadVideoToCloudinary,
  deleteFromCloudinary,
} = require("../../utils/cloudinaryUpload");
const { getClient } = require("../../config/redis");
const { cleanText } = require("../../utils/profanityFilter");
const settingsService = require("../settings/settings.service");

const MIN_DURATION = 60;
const MAX_DURATION = 120;
const MAX_TOTAL_PITCHES = 3;
const PITCH_EXPIRY_DAYS = 30;

const FEED_TTL = 5 * 60; // 5 min
const FEED_PAGE_SIZE = 5;

const uploadPitch = async (founderId, file, body) => {
  if (!file) throw new ApiError(400, "Video file required");

  const settings = await settingsService.getSettings().catch(() => ({}));
  if (settings.uploadsEnabled === false) {
    throw new ApiError(403, "Pitch uploads are temporarily disabled by admin");
  }
  const maxPitches = settings.maxPitchesPerFounder || MAX_TOTAL_PITCHES;
  const expiryDays = settings.pitchExpiryDays || PITCH_EXPIRY_DAYS;

  const founder = await User.findById(founderId);
  if (!founder) throw new ApiError(404, "Founder not found");
  if (founder.role !== "founder") {
    throw new ApiError(403, "Only founders can upload pitches");
  }
  if (founder.verificationLevel < 2) {
    throw new ApiError(403, "Verify phone before uploading");
  }

  const totalPitches = await Video.countDocuments({
    founderId,
    status: { $in: ["active", "processing", "paused"] },
  });
  if (totalPitches >= maxPitches) {
    throw new ApiError(400, `Max ${maxPitches} active pitches allowed`);
  }

  const activePitch = await Video.findOne({ founderId, status: "active" });
  if (activePitch) {
    throw new ApiError(
      400,
      "You already have an active pitch. Pause it first.",
    );
  }

  const uploaded = await uploadVideoToCloudinary(file.path);

  // Validate duration
  const dur = Math.round(uploaded.duration || 0);
  if (dur < MIN_DURATION || dur > MAX_DURATION) {
    await deleteFromCloudinary(uploaded.publicId, "video");
    throw new ApiError(
      400,
      `Video must be between ${MIN_DURATION} and ${MAX_DURATION} seconds (got ${dur}s)`,
    );
  }

  // Build HLS URL — Cloudinary HLS streaming format
  const hlsUrl = uploaded.url.replace(/\.[^.]+$/, ".m3u8");

  // Thumbnail — auto generated by Cloudinary at second 1
  const thumbnailUrl = uploaded.url
    .replace("/video/upload/", "/video/upload/so_1,w_640,h_360,c_fill/")
    .replace(/\.[^.]+$/, ".jpg");

  const expiresAt = new Date(Date.now() + expiryDays * 24 * 60 * 60 * 1000);

  const filterOn = settings.profanityFilterEnabled !== false;
  const extraWords = settings.customBannedWords || [];

  const video = await Video.create({
    founderId,
    title: filterOn ? cleanText(body.title, extraWords) : body.title,
    description: filterOn
      ? cleanText(body.description || "", extraWords)
      : body.description || "",
    videoUrl: uploaded.url,
    hlsUrl,
    thumbnailUrl,
    cloudinaryPublicId: uploaded.publicId,
    duration: dur,
    industry: body.industry || founder.industry,
    fundingStage: body.fundingStage || founder.fundingStage,
    askAmount: Number(body.askAmount) || 0,
    equityOffered: Number(body.equityOffered) || 0,
    visibility:
      body.visibility === "investors-only" ? "investors-only" : "everyone",
    status: "active",
    expiresAt,
  });

  founder.activePitchId = video._id;
  await founder.save({ validateBeforeSave: false });

  // Auto-flag title/description for admin review if they had profanity
  try {
    const moderation = require("../moderation/moderation.service");
    moderation
      .flagIfNeeded({
        contentType: "video",
        contentId: video._id,
        authorId: founderId,
        text: `${body.title || ""} ${body.description || ""}`,
        extraWords,
      })
      .catch(() => {});
  } catch {}

  // Invalidate feed cache
  await invalidateFeedCache();
  return video;
};

const invalidateFeedCache = async () => {
  try {
    const redis = getClient();
    const keys = await redis.keys("feed:*");
    if (keys.length) await redis.del(...keys);
  } catch (e) {
    console.warn("⚠️  Feed cache invalidate failed:", e.message);
  }
};

// Invalidate only a specific user's feed cache entries
const invalidateUserFeedCache = async (userId) => {
  try {
    const redis = getClient();
    const keys = await redis.keys(`feed:${userId}:*`);
    if (keys.length) await redis.del(...keys);
  } catch (e) {
    console.warn("⚠️  User feed cache invalidate failed:", e.message);
  }
};

const buildFeedQuery = async (userId) => {
  const user = await User.findById(userId);
  if (!user) throw new ApiError(404, "User not found");

  const blocked = user.blockedUsers || [];
  const seen = await Video.find({
    $or: [{ notInterested: userId }],
  }).distinct("_id");

  const query = {
    status: "active",
    expiresAt: { $gt: new Date() },
    _id: { $nin: seen },
    founderId: { $nin: blocked }, // exclude blocked users only (NOT self)
  };

  // Founders can only see pitches marked "everyone" (not "investors-only")
  if (user.role === "founder") {
    query.visibility = { $ne: "investors-only" };
  }

  if (user.preferredIndustries?.length) {
    query.$or = [
      { industry: { $in: user.preferredIndustries } },
      { industry: "" },
    ];
  }
  return query;
};

const getFeed = async (investorId, { cursor, limit = FEED_PAGE_SIZE } = {}) => {
  limit = Math.min(Number(limit) || FEED_PAGE_SIZE, 20);

  const cacheKey = `feed:${investorId}:${cursor || "start"}:${limit}`;
  try {
    const redis = getClient();
    const cached = await redis.get(cacheKey);
    if (cached) return JSON.parse(cached);
  } catch {}

  const baseQuery = await buildFeedQuery(investorId);
  if (cursor) {
    baseQuery._id = { ...(baseQuery._id || {}), $lt: cursor };
  }

  const videos = await Video.find(baseQuery)
    .sort({ isBoosted: -1, createdAt: -1, _id: -1 })
    .limit(limit + 1)
    .populate("founderId", "name avatar companyName industry isVerified")
    .lean();

  const hasMore = videos.length > limit;
  const items = hasMore ? videos.slice(0, limit) : videos;
  const nextCursor = hasMore ? items[items.length - 1]._id : null;

  // Compute accurate comment counts for the videos in this page
  const Comment = require("../comment/comment.model");
  const videoIds = items.map((v) => v._id);
  const commentCounts = {};
  try {
    const counts = await Comment.aggregate([
      {
        $match: {
          videoId: { $in: videoIds },
          parentId: null,
          isDeleted: false,
          isHidden: false,
        },
      },
      { $group: { _id: "$videoId", count: { $sum: 1 } } },
    ]);
    counts.forEach((c) => {
      commentCounts[c._id.toString()] = c.count;
    });
  } catch {}

  // Add isLiked / isSaved booleans + accurate counts for the requesting user
  const uid = investorId.toString();
  const enriched = items.map((v) => ({
    ...v,
    isLiked: (v.likes || []).some((id) => id.toString() === uid),
    isSaved: (v.saves || []).some((id) => id.toString() === uid),
    likeCount: (v.likes || []).length,
    saveCount: (v.saves || []).length,
    commentCount: commentCounts[v._id.toString()] ?? v.commentCount ?? 0,
  }));

  const result = { videos: enriched, nextCursor, hasMore };

  try {
    const redis = getClient();
    await redis.set(cacheKey, JSON.stringify(result), "EX", FEED_TTL);
  } catch {}

  return result;
};

const getVideoById = async (videoId) => {
  const video = await Video.findById(videoId).populate(
    "founderId",
    "name avatar companyName industry isVerified bio website linkedIn",
  );
  if (!video) throw new ApiError(404, "Video not found");

  // Ensure commentCount is accurate (backfill for legacy videos)
  try {
    const Comment = require("../comment/comment.model");
    const realCount = await Comment.countDocuments({
      videoId: video._id,
      parentId: null,
      isDeleted: false,
      isHidden: false,
    });
    if (video.commentCount !== realCount) {
      video.commentCount = realCount;
      await video.save({ validateBeforeSave: false });
    }
  } catch {}

  return video;
};

const updateVideo = async (videoId, founderId, updates) => {
  const allowed = [
    "title",
    "description",
    "askAmount",
    "equityOffered",
    "industry",
  ];
  const sanitized = {};
  for (const k of allowed)
    if (updates[k] !== undefined) sanitized[k] = updates[k];
  if (sanitized.title) sanitized.title = cleanText(sanitized.title);
  if (sanitized.description)
    sanitized.description = cleanText(sanitized.description);

  const video = await Video.findOneAndUpdate(
    { _id: videoId, founderId },
    sanitized,
    { new: true, runValidators: true },
  );
  if (!video) throw new ApiError(404, "Video not found");
  await invalidateFeedCache();
  return video;
};

const deleteVideo = async (videoId, founderId) => {
  const video = await Video.findOne({ _id: videoId, founderId });
  if (!video) throw new ApiError(404, "Video not found");
  if (video.cloudinaryPublicId) {
    await deleteFromCloudinary(video.cloudinaryPublicId, "video");
  }
  await video.deleteOne();
  await User.findByIdAndUpdate(founderId, { $unset: { activePitchId: 1 } });
  await invalidateFeedCache();
};

const likeVideo = async (videoId, investorId) => {
  const video = await Video.findById(videoId);
  if (!video) throw new ApiError(404, "Video not found");

  const liked = video.likes.some(
    (id) => id.toString() === investorId.toString(),
  );
  if (liked) {
    video.likes = video.likes.filter(
      (id) => id.toString() !== investorId.toString(),
    );
  } else {
    video.likes.push(investorId);
    video.notInterested = video.notInterested.filter(
      (id) => id.toString() !== investorId.toString(),
    );
  }
  await video.save();

  // Invalidate this user's feed cache so refreshed page reflects the like
  await invalidateUserFeedCache(investorId);

  // Notify founder on new like
  if (!liked && video.founderId.toString() !== investorId.toString()) {
    try {
      const notif = require("../notification/notification.service");
      const investor = await User.findById(investorId).select("name");
      notif
        .send(video.founderId, {
          type: "like",
          title: `${investor?.name || "An investor"} liked your pitch`,
          body: video.title,
          data: {
            videoId: video._id.toString(),
            investorId: investorId.toString(),
          },
        })
        .catch(() => {});
    } catch {}
  }
  return { liked: !liked, totalLikes: video.likes.length };
};

const saveVideo = async (videoId, investorId) => {
  const video = await Video.findById(videoId);
  if (!video) throw new ApiError(404, "Video not found");
  const saved = video.saves.some(
    (id) => id.toString() === investorId.toString(),
  );
  if (saved) {
    video.saves = video.saves.filter(
      (id) => id.toString() !== investorId.toString(),
    );
  } else {
    video.saves.push(investorId);
  }
  await video.save();

  // Invalidate this user's feed cache so refreshed page reflects the save
  await invalidateUserFeedCache(investorId);

  // Notify founder on new save
  if (!saved && video.founderId.toString() !== investorId.toString()) {
    try {
      const notif = require("../notification/notification.service");
      const investor = await User.findById(investorId).select("name");
      notif
        .send(video.founderId, {
          type: "save",
          title: `${investor?.name || "An investor"} saved your pitch`,
          body: video.title,
          data: {
            videoId: video._id.toString(),
            investorId: investorId.toString(),
          },
        })
        .catch(() => {});
    } catch {}
  }
  return { saved: !saved, totalSaves: video.saves.length };
};

const markNotInterested = async (videoId, investorId) => {
  const video = await Video.findById(videoId);
  if (!video) throw new ApiError(404, "Video not found");
  if (
    !video.notInterested.some((id) => id.toString() === investorId.toString())
  ) {
    video.notInterested.push(investorId);
  }
  await video.save();
  return { notInterested: true };
};

const logView = async (videoId, investorId, watchedSeconds = 0) => {
  const video = await Video.findById(videoId);
  if (!video) throw new ApiError(404, "Video not found");

  const isUnique = !video.uniqueViews.some(
    (id) => id.toString() === investorId.toString(),
  );
  if (isUnique) video.uniqueViews.push(investorId);

  // Increment total view count in the DB so it shows in feeds/analytics.
  video.views = (video.views || 0) + 1;

  if (watchedSeconds > 0) {
    video.watchTimeData.push({
      investorId,
      watchedSeconds: Math.min(watchedSeconds, video.duration),
      completedAt: watchedSeconds >= video.duration * 0.95 ? new Date() : null,
    });
  }
  await video.save();
  return { logged: true, views: video.views };
};

const getMyPitches = async (founderId) => {
  const videos = await Video.find({ founderId }).sort({ createdAt: -1 }).lean();
  return enrichWithCommentCounts(videos, founderId);
};

// Public — active pitches for a given founder (for their profile page)
const getUserPitches = async (founderId, viewerId) => {
  const videos = await Video.find({
    founderId,
    status: "active",
    visibility: { $ne: "investors-only" },
  })
    .sort({ createdAt: -1 })
    .lean();
  return enrichWithCommentCounts(videos, viewerId || founderId);
};

const getSavedPitches = async (investorId) => {
  const videos = await Video.find({ saves: investorId, status: "active" })
    .sort({ createdAt: -1 })
    .populate("founderId", "name avatar companyName industry isVerified")
    .lean();
  return enrichWithCommentCounts(videos, investorId);
};

// Helper — add commentCount + isLiked/isSaved + counts to a list of videos
const enrichWithCommentCounts = async (videos, userId) => {
  if (!videos.length) return videos;
  const Comment = require("../comment/comment.model");
  const videoIds = videos.map((v) => v._id);
  const commentCounts = {};
  try {
    const counts = await Comment.aggregate([
      {
        $match: {
          videoId: { $in: videoIds },
          parentId: null,
          isDeleted: false,
          isHidden: false,
        },
      },
      { $group: { _id: "$videoId", count: { $sum: 1 } } },
    ]);
    counts.forEach((c) => {
      commentCounts[c._id.toString()] = c.count;
    });
  } catch {}

  const uid = userId?.toString();
  return videos.map((v) => ({
    ...v,
    isLiked: uid ? (v.likes || []).some((id) => id.toString() === uid) : false,
    isSaved: uid ? (v.saves || []).some((id) => id.toString() === uid) : false,
    likeCount: (v.likes || []).length,
    saveCount: (v.saves || []).length,
    commentCount: commentCounts[v._id.toString()] ?? v.commentCount ?? 0,
  }));
};

const getAnalytics = async (videoId, founderId) => {
  const video = await Video.findOne({ _id: videoId, founderId });
  if (!video) throw new ApiError(404, "Video not found");

  const totalViews = video.views;
  const uniqueViewers = video.uniqueViews.length;
  const totalLikes = video.likes.length;
  const totalSaves = video.saves.length;
  const watchData = video.watchTimeData;
  const avgWatchTime =
    watchData.length === 0
      ? 0
      : Math.round(
          watchData.reduce((s, w) => s + (w.watchedSeconds || 0), 0) /
            watchData.length,
        );
  const completionRate =
    watchData.length === 0
      ? 0
      : Math.round(
          (watchData.filter((w) => w.completedAt).length / watchData.length) *
            100,
        );

  return {
    videoId: video._id,
    title: video.title,
    duration: video.duration,
    totalViews,
    uniqueViewers,
    totalLikes,
    totalSaves,
    avgWatchTime,
    completionRate,
    notInterestedCount: video.notInterested.length,
  };
};

const renewPitch = async (videoId, founderId) => {
  const video = await Video.findOne({ _id: videoId, founderId });
  if (!video) throw new ApiError(404, "Video not found");
  video.expiresAt = new Date(
    Date.now() + PITCH_EXPIRY_DAYS * 24 * 60 * 60 * 1000,
  );
  video.isRenewed = true;
  if (video.status === "expired") video.status = "active";
  await video.save();
  await invalidateFeedCache();
  return video;
};

// Trending — most liked + saved in last 7 days
const getTrending = async ({ limit = 10 } = {}) => {
  limit = Math.min(Number(limit) || 10, 30);
  const since = new Date(Date.now() - 7 * 24 * 60 * 60 * 1000);
  const videos = await Video.aggregate([
    {
      $match: {
        status: "active",
        expiresAt: { $gt: new Date() },
        createdAt: { $gte: since },
      },
    },
    {
      $addFields: {
        score: {
          $add: [
            { $size: { $ifNull: ["$likes", []] } },
            { $multiply: [{ $size: { $ifNull: ["$saves", []] } }, 2] },
            { $multiply: [{ $cond: ["$isBoosted", 50, 0] }, 1] },
          ],
        },
      },
    },
    { $sort: { score: -1, createdAt: -1 } },
    { $limit: limit },
    {
      $lookup: {
        from: "users",
        localField: "founderId",
        foreignField: "_id",
        as: "founder",
      },
    },
    { $unwind: "$founder" },
    {
      $project: {
        title: 1,
        description: 1,
        videoUrl: 1,
        hlsUrl: 1,
        thumbnailUrl: 1,
        duration: 1,
        industry: 1,
        fundingStage: 1,
        askAmount: 1,
        equityOffered: 1,
        views: 1,
        score: 1,
        createdAt: 1,
        likes: 1,
        saves: 1,
        founderId: {
          _id: "$founder._id",
          name: "$founder.name",
          avatar: "$founder.avatar",
          companyName: "$founder.companyName",
          isVerified: "$founder.isVerified",
        },
      },
    },
  ]);
  return videos;
};

// Search videos directly
const searchVideos = async ({
  q,
  industry,
  fundingStage,
  minAsk,
  maxAsk,
  limit = 20,
  cursor,
}) => {
  limit = Math.min(Number(limit) || 20, 50);
  const filter = {
    status: "active",
    expiresAt: { $gt: new Date() },
  };
  if (industry) filter.industry = industry;
  if (fundingStage) filter.fundingStage = fundingStage;
  if (minAsk)
    filter.askAmount = { ...(filter.askAmount || {}), $gte: Number(minAsk) };
  if (maxAsk)
    filter.askAmount = { ...(filter.askAmount || {}), $lte: Number(maxAsk) };
  if (q) {
    filter.$or = [
      { title: new RegExp(q, "i") },
      { description: new RegExp(q, "i") },
    ];
  }
  if (cursor) filter._id = { $lt: cursor };

  const videos = await Video.find(filter)
    .sort({ _id: -1 })
    .limit(limit + 1)
    .populate("founderId", "name avatar companyName isVerified")
    .lean();
  const hasMore = videos.length > limit;
  return {
    videos: hasMore ? videos.slice(0, limit) : videos,
    nextCursor: hasMore ? videos[limit - 1]._id : null,
    hasMore,
  };
};

const togglePause = async (videoId, founderId) => {
  const video = await Video.findOne({ _id: videoId, founderId });
  if (!video) throw new ApiError(404, "Video not found");
  if (video.status === "active") video.status = "paused";
  else if (video.status === "paused") video.status = "active";
  await video.save();
  await invalidateFeedCache();
  return video;
};

module.exports = {
  uploadPitch,
  getFeed,
  getTrending,
  searchVideos,
  getVideoById,
  updateVideo,
  deleteVideo,
  likeVideo,
  saveVideo,
  markNotInterested,
  logView,
  getMyPitches,
  getUserPitches,
  getSavedPitches,
  getAnalytics,
  renewPitch,
  togglePause,
  invalidateFeedCache,
};
